# Generated by Django 4.2.7 on 2023-11-25 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('edition', models.IntegerField()),
                ('year', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('thumbnail', models.BinaryField(null=True)),
                ('grade', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dados_complementares',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default=None, max_length=30, unique=True)),
                ('cpf', models.CharField(max_length=11)),
                ('name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
                ('password', models.CharField(default=None, max_length=255)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('isbn', models.BigIntegerField()),
                ('cpf', models.BigIntegerField()),
                ('availability', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('idReview', models.IntegerField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('comment', models.TextField()),
                ('bookIsbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('userCpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('idLoan', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('state', models.CharField(max_length=50)),
                ('bookIsbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.book')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_borrower', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_as_lender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
